<a href="https://colab.research.google.com/github/grownsandip/ML_Algo/blob/main/SVM_algorithm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**SVM algorithm works on the smaller but coplex datasets**

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets

loading iris datasets into the variable iris

In [ ]:
iris=datasets.load_iris()

seperating data and target data from iris into x and y

In [ ]:
x=iris.data
y=iris.target
names=iris.target_names

In [ ]:
x.shape


(150, 4)

In [ ]:
y.shape

(150,)

In [ ]:
df=pd.DataFrame(x,columns=iris.feature_names)
df['species']=iris.target
df['species']=df['species'].replace(to_replace=[0,1,2],value=['setpsa','versicolor','virginica'])

In [ ]:
df

EDA exploratory data analysis using seaborn

In [ ]:
import seaborn as sns
sns.pairplot(data=df,hue='species',palette='Set2')

as we have seen data cannot be classified using single line we need plane but before that we need data to be sperated as traing and testing samples

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=1)

showing the training and testing datasets

In [ ]:
print(x_train.shape,y_train.shape)
print(x_test.shape,y_test.shape)

(120, 4) (120,)
(30, 4) (30,)


applying the svm in the training data sets

In [ ]:
from sklearn.svm import SVC
svm=SVC(kernel='linear',random_state=0)
svm.fit(x_train,y_train)

SVC(kernel='linear', random_state=0)

now we check how is the prediction going on

In [ ]:
pred=svm.predict(x_test)

In [ ]:
pred

array([0, 1, 1, 0, 2, 1, 2, 0, 0, 2, 1, 0, 2, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 2, 1, 0, 0, 1, 2])

now we will see how accurately model is predicting using sklearn

In [ ]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
accuracy_score(y_test,pred)

1.0

now i want to see the confusion matrix if it containes no true positive or no true negetive value than our model has accuracy score 1 which means it is doing 100% accurate predictions

In [ ]:
confusion_matrix(y_test,pred)

now we will use rbf kernel on same data set to see the performance

In [ ]:
svm_rbf=SVC(kernel='rbf',random_state=0)
svm_rbf.fit(x_train,y_train)
rbf_pred=svm_rbf.predict(x_test)

In [ ]:
rbf_pred

array([0, 1, 1, 0, 2, 1, 2, 0, 0, 2, 1, 0, 2, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       2, 0, 2, 1, 0, 0, 1, 2])

In [ ]:
accuracy_score(y_test,rbf_pred)

0.9666666666666667

In [ ]:
confusion_matrix(y_test,rbf_pred)

array([[11,  0,  0],
       [ 0, 12,  1],
       [ 0,  0,  6]])